### ISSUE TITLE
Task Creation: Support Difficulty

### ISSUE THREAD

**Issue by gabrielkrell** [HabitRPG/habitica-zapier#4]
In the create task action, there should be a "Difficulty" option that lets you pick Trivial/Easy/Medium/Hard.  Currently there is no such action, and all created tasks are set as Easy.

**Comment by Majed6** [comment]
See https://github.com/HabitRPG/habitica-zapier/pull/3 . If that pr is too hack-y for an official zapier integration, feel free to recreate it without nerdamer. 

PS: If the team don't mind I could also invite you to my personal habitica-zapier integration.

**Comment by gabrielkrell** [comment]
Thanks @Majed6; I made this and then immediately saw your PR lol. I'll chill out for now, hopefully it'll just get merged.

**Comment by Alys** [comment]
Code to support difficulty (`priority`) has been accepted from @Majed6's PR https://github.com/HabitRPG/habitica-zapier/pull/3

It's not yet available for use but will be soon in a beta version of the integration. First I need to sort out some problems I'm having with testing. Once it's ready for use, I'll comment here and close this issue.

**Comment by Alys** [comment]
Difficulty (priority) support is now available in version 2.1.0 of the beta zapier integration. The invite link is in the wiki's [Zapier](https://habitica.fandom.com/wiki/Zapier) page in the [Beta Development Version section](https://habitica.fandom.com/wiki/Zapier#Beta_Development_Version) at the bottom of the page.
